"""
Pipeline API endpoint — /api/pipeline/full/

Accepts document uploads and runs the full validation pipeline.
Returns the enhanced response schema with all analysis dimensions.

Request/Response validation via Pydantic v2 models.
"""
from __future__ import annotations

import logging
import os
import pathlib
import tempfile
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, File, HTTPException, Query, UploadFile
from fastapi.responses import JSONResponse
from starlette.concurrency import run_in_threadpool

from app.core.dependencies import get_request_id, get_validator
from app.schemas.responses import ErrorResponse, PipelineFullResponse
from src.exceptions import DocumentValidatorError, NonAcademicDocumentError, UnsupportedFileTypeError
from src.pipeline import DocumentValidator

router = APIRouter()
logger = logging.getLogger(__name__)

# ─── Allowed content types ───────────────────────────────────
_ALLOWED_TYPES = {
    "image/jpeg", "image/jpg", "image/png", "image/webp",
    "image/tiff", "application/pdf",
}


def _validate_upload(file) -> None:
    """Validate the uploaded file type."""
    content_type = file.content_type or ""
    if not any(content_type.startswith(t.split("/")[0]) for t in _ALLOWED_TYPES) and content_type not in _ALLOWED_TYPES:
        raise UnsupportedFileTypeError(content_type)


def _validate_sync(validator, image_path: str) -> dict:
    """Synchronous full pipeline validation — runs in a thread pool."""
    return validator.validate(image_path)


@router.post(
    "/full/",
    response_model=PipelineFullResponse,
    responses={
        400: {"model": ErrorResponse, "description": "Invalid file type or non-academic document"},
        500: {"model": ErrorResponse, "description": "Internal pipeline error"},
    },
    summary="Run full document validation pipeline",
    description=(
        "Accepts a document image (JPEG, PNG, PDF) and runs: "
        "CNN forgery detection → OCR extraction (Gemini) → "
        "Institution recognition → Document classification → "
        "5-dimensional format validation. Returns all results in a unified response."
    ),
)
async def validate_document_full(
    file: UploadFile = File(..., description="Document image or PDF to validate"),
    validator: DocumentValidator = Depends(get_validator),
    request_id: str = Depends(get_request_id),
):
    """Full document validation pipeline endpoint."""

    # Validate file type
    try:
        _validate_upload(file)
    except UnsupportedFileTypeError as exc:
        raise HTTPException(status_code=400, detail=exc.to_dict())

    # Read file content
    suffix = pathlib.Path(file.filename).suffix if file.filename else ".jpg"
    content = await file.read()

    if not content:
        raise HTTPException(
            status_code=400,
            detail={"error": "EMPTY_FILE", "message": "Uploaded file is empty"},
        )

    # Write to temp file for pipeline processing
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temp_file:
        temp_file.write(content)
        temp_path = temp_file.name

    try:
        # Offload synchronous pipeline to thread pool (non-blocking)
        result = await run_in_threadpool(_validate_sync, validator, temp_path)

        # Inject the request_id (generated by middleware)
        result["request_id"] = request_id
        result["timestamp"] = datetime.now(timezone.utc).isoformat()

        return JSONResponse(content=result)

    except NonAcademicDocumentError as exc:
        raise HTTPException(status_code=400, detail=exc.to_dict())

    except DocumentValidatorError as exc:
        logger.error(f"Pipeline error for request {request_id}: {exc!r}")
        raise HTTPException(status_code=500, detail=exc.to_dict())

    except Exception as exc:
        logger.exception(f"Unexpected error in pipeline for request {request_id}")
        raise HTTPException(
            status_code=500,
            detail={
                "error": "INTERNAL_ERROR",
                "message": f"Pipeline failed: {str(exc)[:300]}",
                "request_id": request_id,
            },
        )

    finally:
        # Clean up temp file
        if os.path.exists(temp_path):
            try:
                os.remove(temp_path)
            except OSError:
                pass

