"""add roles usage tracking and institution records

Revision ID: 7b7a1207d6b1
Revises: 
Create Date: 2026-02-23 12:41:05.504596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7a1207d6b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_paid')
        batch_op.drop_column('validation_count')

    # ### end Alembic commands ###
